In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [4]:
data = pd.read_excel('Base_Data.xlsx')

In [5]:
data

,Team,League,W,L,ERAâ–²,G,GS,SV,SVO,IP,H,R,ER,HR,BB,SO,AVG,WHIP,Unnamed: 18
0,1,Houston Astros,AL,103,59,3.11,162,162,46,67,1455.0,1164,534,503,152,435,1687,0.217,1.10
1,2,Los Angeles Dodgers,NL,92,71,3.38,163,163,48,74,1476.0,1279,610,554,179,422,1565,0.230,1.15
2,3,Chicago Cubs,NL,95,68,3.65,163,163,46,65,1476.1,1319,645,598,157,622,1333,0.240,1.31
3,4,Arizona Diamondbacks,NL,82,80,3.72,162,162,39,66,1463.0,1313,644,605,174,522,1448,0.239,1.25
4,5,Milwaukee Brewers,NL,96,67,3.73,163,163,49,74,1461.0,1259,659,606,173,553,1428,0.233,1.24
5,6,Tampa Bay Rays,AL,90,72,3.74,162,162,52,74,1448.1,1236,646,602,164,501,1421,0.230,1.20
6,7,Atlanta Braves,NL,90,72,3.75,162,162,40,60,1456.2,1236,657,607,153,635,1423,0.229,1.28
7,8,Boston Red Sox,AL,108,54,3.75,162,162,46,66,1458.2,1305,647,608,176,512,1558,0.237,1.25
8,9,Cleveland Indians,AL,91,71,3.77,162,162,41,58,1457.1,1349,648,611,200,407,1544,0.242,1.20
9,10,New York Yankees,AL,100,62,3.78,162,162,49,67,1456.1,1311,669,611,177,494,1634,0.237,1.24
10,11,Oakland Athletics,AL,97,65,3.81,162,162,44,62,1465.2,1303,674,621,184,474,1237,0.236,1.21
11,12,St. Louis Cardinals,NL,88,74,3.85,162,162,43,64,1455.1,1354,691,622,144,593,1337,0.246,1.34
12,13,San Francisco Giants,NL,73,89,3.95,162,162,36,66,1461.1,1387,699,641,156,524,1269,0.251,1.31
13,14,Pittsburgh Pirates,NL,82,79,4.00,161,161,40,60,1434.0,1380,693,637,174,497,1336,0.251,1.31
14,15,Washington Nationals,NL,82,80,4.04,162,162,40,54,1446.0,1320,682,649,198,487,1417,0.242,1.25
15,16,New York Mets,NL,77,85,4.07,162,162,41,59,1460.2,1364,707,661,185,484,1446,0.246,1.27
16,17,Seattle Mariners,AL,89,73,4.13,162,162,60,81,1448.2,1396,711,664,195,400,1328,0.252,1.24
17,18,Philadelphia Phillies,NL,80,82,4.14,162,162,44,64,1445.2,1366,728,665,171,500,1465,0.249,1.29
18,19,Los Angeles Angels,AL,80,82,4.15,162,162,35,61,1437.1,1353,722,662,205,546,1386,0.248,1.32
19,20,Colorado Rockies,NL,91,72,4.33,163,163,51,78,1452.1,1377,745,699,184,525,1409,0.250,1.31
20,21,San Diego Padres,NL,66,96,4.40,162,162,36,53,1457.0,1430,767,713,185,519,1399,0.256,1.34
21,22,Minnesota Twins,AL,78,84,4.50,162,162,37,65,1443.1,1425,775,721,198,573,1377,0.256,1.38
22,23,Detroit Tigers,AL,64,98,4.58,162,162,37,61,1425.1,1423,796,726,216,491,1215,0.258,1.34
23,24,Cincinnati Reds,NL,67,95,4.63,162,162,38,57,1441.0,1491,819,741,228,532,1258,0.266,1.40
24,25,Miami Marlins,NL,63,98,4.76,161,161,30,53,1442.0,1388,809,762,192,605,1249,0.254,1.38
25,26,Chicago White Sox,AL,62,100,4.83,162,162,34,53,1437.0,1404,848,771,196,653,1259,0.254,1.43
26,27,Toronto Blue Jays,AL,73,89,4.85,162,162,39,59,1433.2,1476,832,772,208,551,1298,0.265,1.41
27,28,Texas Rangers,AL,67,95,4.92,162,162,42,56,1431.0,1516,848,783,222,491,1121,0.271,1.40
28,29,Kansas City Royals,AL,58,104,4.94,162,162,33,57,1432.0,1542,833,786,205,549,1157,0.275,1.46
29,30,Baltimore Orioles,AL,47,115,5.18,162,162,28,46,1431.0,1552,892,824,234,589,1203,0.276,1.50

In [7]:
def filter(data):
    headings = list(data)
    column_list = []
    for col in headings:
        print("\n")
        print("The current column indexed is ", col)
        res = input("Would you like to drop this column?")
        if res=="y":
            column = str(col)
            column_list.append(column)
            print("I just dropped that for you...", col)
        elif res=="n":
            print("I kept that column for you...", col)
        else:
            print("That was not a valid response... For your safety and sanity I kept that column")

In [8]:
column_list = filter(data)
data = data.drop(column_list, axis=1)

The current column indexed is  Team
Would you like to drop this column?n
I kept that column for you... Team


The current column indexed is  League
Would you like to drop this column?y
I just dropped that for you... League


The current column indexed is  W
Would you like to drop this column?y
I just dropped that for you... W


The current column indexed is  L
Would you like to drop this column?y
I just dropped that for you... L


The current column indexed is  ERAâ–²
Would you like to drop this column?y
I just dropped that for you... ERAâ–²


The current column indexed is  G
Would you like to drop this column?y
I just dropped that for you... G


The current column indexed is  GS
Would you like to drop this column?n
I kept that column for you... GS


The current column indexed is  SV
Would you like to drop this column?y
I just dropped that for you... SV


The current column indexed is  SVO
Would you like to drop this column?y
I just dropped that for you... SVO


The current column indexed is  IP
Would you like to drop this column?n
I kept that column for you... IP


The current column indexed is  H
Would you like to drop this column?y
I just dropped that for you... H


The current column indexed is  R
Would you like to drop this column?y
I just dropped that for you... R


The current column indexed is  ER
Would you like to drop this column?y
I just dropped that for you... ER


The current column indexed is  HR
Would you like to drop this column?n
I kept that column for you... HR


The current column indexed is  BB
Would you like to drop this column?y
I just dropped that for you... BB


The current column indexed is  SO
Would you like to drop this column?y
I just dropped that for you... SO


The current column indexed is  AVG
Would you like to drop this column?y
I just dropped that for you... AVG


The current column indexed is  WHIP
Would you like to drop this column?y
I just dropped that for you... WHIP


The current column indexed is  Unnamed: 18
Would you like to drop this column?y
I just dropped that for you... Unnamed: 18

In [9]:
data

    Team   GS  IP   HR
0      1  162  67  503
1      2  163  74  554
2      3  163  65  598
3      4  162  66  605
4      5  163  74  606
5      6  162  74  602
6      7  162  60  607
7      8  162  66  608
8      9  162  58  611
9     10  162  67  611
10    11  162  62  621
11    12  162  64  622
12    13  162  66  641
13    14  161  60  637
14    15  162  54  649
15    16  162  59  661
16    17  162  81  664
17    18  162  64  665
18    19  162  61  662
19    20  163  78  699
20    21  162  53  713
21    22  162  65  721
22    23  162  61  726
23    24  162  57  741
24    25  161  53  762
25    26  162  53  771
26    27  162  59  772
27    28  162  56  783
28    29  162  57  786
29    30  162  46  824

In [ ]:
dataset2